name: OozeRPG
version: 0.0.1
api-version: 1.13
author: MrMarshall
website: https://mrmarshall.dev/
depends: [Vault]
main: dev.mrmarshall.oozerpg.OozeRPG

commands:
  race:
    description: Opens a GUI to select a race
  skills:
    description: Opens a GUI to view and upgrade skills